作業目標<br>
計算有缺失值的資料，統計量實作<br>
作業重點<br>
當遇到缺失值有函式可以處理，不須額外寫程式刪除<br>
計算統計量時不能出現缺失值

題目:<br>
english_score = np.array([55,89,76,65,48,70])<br>
math_score = np.array([60,85,60,68,np.nan,60])<br>
chinese_score = np.array([65,90,82,72,66,77])<br>
上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，今天第五位同學因某原因沒來考試，導致數學成績缺值，運用上列數據回答下列問題。<br>
1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
3. 用補考後資料找出與國文成績相關係數最高的學科?

In [2]:
import numpy as np

In [3]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

In [3]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?

In [13]:
#english score
#英文成績平均
np.mean(english_score)

67.16666666666667

In [8]:
#英文成績對大值
np.nanmax(english_score)

89

In [9]:
#英文成績最小值
np.nanmin(english_score)

48

In [10]:
#英文成績標準差
np.nanstd(english_score)

13.433995020924426

In [14]:
#math score
#數學成績平均
np.nanmean(math_score)

66.6

In [15]:
#數學成績對大值
np.nanmax(math_score)

85.0

In [16]:
#數學成績最小值
np.nanmin(math_score)

60.0

In [17]:
#數學成績標準差
np.nanstd(math_score)

9.707728879609279

In [18]:
#chinese score
#中文成績平均
np.nanmean(chinese_score)

75.33333333333333

In [19]:
#中文成績對大值
np.nanmax(chinese_score)

90

In [20]:
#中文成績對小值
np.nanmin(chinese_score)

65

In [21]:
#中文成績標準差
np.nanstd(chinese_score)

8.825468196582484

In [4]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?

In [22]:
math_score[4] = 55

In [23]:
math_score

array([60., 85., 60., 68., 55., 60.])

In [24]:
print(f'數學平均值:{np.nanmean(math_score)},最大值:{np.nanmax(math_score)},最小值:{np.nanmin(math_score)},標準差:{np.nanstd(math_score)}')

數學平均值:64.66666666666667,最大值:85.0,最小值:55.0,標準差:9.860132971832694


In [5]:
#3. 用補考後資料找出與國文成績相關係數最高的學科?

In [25]:
np.corrcoef(chinese_score,math_score)

array([[1.        , 0.74056803],
       [0.74056803, 1.        ]])

In [26]:
np.corrcoef(chinese_score,english_score)

array([[1.        , 0.97792828],
       [0.97792828, 1.        ]])

In [ ]:
#英文